version: '3'

services:
  reviews:
    image: justindchan/fec_reviews2
    depends_on:
      - 'database'
    ports:
      - '3306:3306'
    restart: always

  database:
    image: justindchan/mysql:firsttry
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: root
      MYSQL_DATABASE: Reviews

  # seed:
  #   build:
  #     context: .
  #     dockerfile: ./seed/Dockerfile
  #   # image: justindchan/fec_seed:latest
  #   depends_on:
  #     - 'database'

  proxy:
    image: justindchan/fec_proxy
    ports:
      - '3000:3000'

